import { execFileSync } from "node:child_process"
import { mkdtempSync, readFileSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

import { afterEach, beforeEach, describe, expect, it } from "vitest"

const SCRIPT = join(process.cwd(), "scripts", "gen-build-flavor.mjs")

describe("gen-build-flavor script", () => {
  let dir: string
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "fenek-flavor-"))
  })
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  function run(env: Record<string, string>): string {
    execFileSync(process.execPath, [SCRIPT], {
      cwd: dir,
      env: { ...process.env, ...env },
      stdio: ["ignore", "pipe", "pipe"],
    })
    return readFileSync(join(dir, "src", "generated", "build-flavor.ts"), "utf8")
  }

  it("writes the standard flavor by default", () => {
    const out = run({ FENEK_BUILD_FLAVOR: "" }) // empty value = standard; overrides any inherited env
    expect(out).toContain(`export const BUILD_FLAVOR: BuildFlavor = "standard"`)
    expect(out).toContain("Generated by scripts/gen-build-flavor.mjs")
  })

  it("writes the freepro flavor when FENEK_BUILD_FLAVOR=freepro", () => {
    const out = run({ FENEK_BUILD_FLAVOR: "freepro" })
    expect(out).toContain(`export const BUILD_FLAVOR: BuildFlavor = "freepro"`)
  })

  it("rejects unknown flavors and names the offender", () => {
    let caught: unknown
    try {
      run({ FENEK_BUILD_FLAVOR: "premium" })
    } catch (error) {
      caught = error
    }
    expect(caught).toBeDefined()
    const stderr = (caught as { stderr?: Buffer | string }).stderr
    const stderrText = Buffer.isBuffer(stderr) ? stderr.toString() : (stderr ?? "")
    expect(stderrText).toContain("unknown flavor 'premium'")
  })

  it("matches the committed default byte for byte", () => {
    const generated = run({ FENEK_BUILD_FLAVOR: "" })
    const committed = readFileSync(
      join(process.cwd(), "src", "generated", "build-flavor.ts"),
      "utf8",
    )
    expect(generated).toBe(committed)
  })
})
